### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by AaronCSchmitz** [bmaupin/civ5-cheevos-with-mods#1]
Running the PowerShell command in Windows results in gray tiles and a broken camera

![20240531002952_1](https://github.com/bmaupin/civ5-cheevos-with-mods/assets/22008070/1c23fbca-c7f5-4c56-b94c-7451cf25907e)

Running Windows 10 with a Steam version of Civ5

**Comment by bmaupin** [comment]
That's really weird. Do you normally play the DirectX 11 version of the game or DirectX 9?

I did a quick search and it sounds like this issue could be specific to the DirectX 11 version. I guess the only way to know if it's related to the patch would be to uninstall the patch and play the game and see if the issue goes away.

**Comment by AaronCSchmitz** [comment]
DirectX 11, and running the patch on the DirectX 9 executable causes a crash to desktop when loading the main menu

These issues only happen after running the PowerShell command—even on fresh installs—and uninstalling (by verifying the files) makes them go away... I've tested this on both the latest version and legacy versions of Civ5 and the same thing happens

Oddly enough, patching the Tablet executable and running the game in tablet mode works fine though...

**Comment by bmaupin** [comment]
Thanks for the details. That's very strange. I wasn't actually able to test the DirectX 11 version myself since it throws errors for me when I try it in VirtualBox. But when I run the DirectX 11 version (for Windows) in Linux using Proton, it works fine for me. I tested through the regular menu, through the Mods menu without mods, and through the Mods menu with mods. I'm testing with the legacy version.

I do have one last thing to try, because I have seen instances in which Steam kept old versions of files around after switching versions:

1. Install the legacy version of Civ 5 (since I know this works at least in Proton)
2. Run the uninstall steps just to make sure that the the files are clean
3. Install the patch to the DirectX 11 binary (don't bother with DirectX 9, it won't work)
4. Test again with DirectX 11

If it still doesn't work, then it's possible that the patch only works with Proton and not Windows, which would surprise me but certainly isn't impossible.

If that's the case, I did actually create a DirectX 9 patch before I came up with the DirectX 11 patch. It takes a different approach. I did actually test it successfully in Windows 10 with VirtualBox so it should work.

1. Download and unzip the patch script: [patch-civ5.zip](https://github.com/user-attachments/files/15537406/patch-civ5.zip)
2. Run the uninstall steps to make sure the files are clean
3. Install the patch

   ```
   patch-civ5.exe 'C:\Program Files (x86)\Steam\steamapps\common\Sid Meier''s Civilization V\CivilizationV.exe'
   ```
   
   (Update the path as needed)

4. Play the DirectX 9 version

Please let me know if any of the above works (or not) so I can update the documentation for anyone else that may be interested.

... oh one last question, are you using 32-bit or 64-bit Windows? I tested the DirectX 9 version using Windows 10 64-bit.

Thanks!

**Comment by AaronCSchmitz** [comment]
I'm running 64-bit Windows 10

The DirectX 11 patch doesn't work on either the legacy version or the latest version

The DirectX 9 patch works perfectly on both versions (for me, at least)

**Comment by bmaupin** [comment]
I'm glad to hear the DirectX 9 patch worked.

Out of curiosity, would you mind trying the DirectX 9 patch on the DirectX 11 executable? I'm curious if that would work.

Thanks!

**Comment by AaronCSchmitz** [comment]
Running the DirextX 9 patch on the DirectX 11 executable causes a crash when trying to load a game

**Comment by AaronCSchmitz** [comment]
Running the DX9 patch on the DX11 executable causes a crash when trying to load the game, on both the legacy and latest versions

The DX9 patch works fine for the Tablet executable though, on both the legacy and latest versions

**Comment by bmaupin** [comment]
Thanks for all of your help! I just went ahead and removed the DirectX 11 patch instructions. At least the DirectX 9 patch works in Windows. Better than nothing.

**Comment by bmaupin** [comment]
After all this time I finally discovered why the patch worked sometimes and other times it would cause graphical glitches or the game to crash altogether. It was due to something called Steam Custom Executable Generation (CEG). I've updated the readme with steps that should work.
